pull_request_rules:
  - name: rebase and merge when passing all checks
    conditions:
      - base=master
      - status-success="validate commits"
      - status-success="bionic"
      - status-success="bionic - 32 bit"
      - status-success="bionic - gcc-8,distcheck"
      - status-success="bionic - clang-6.0"
      - status-success="coverage"
      - status-success="focal"
      - status-success="centos7"
      - status-success="centos8"
      - status-success="fedora33"
      - status-success="fedora34"
      - status-success="fedora34 - asan"
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "approved-reviews-by=@flux-framework/core"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~=^\[*[Ww][Ii][Pp]
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
